name: "Audentia-Protect"
main: fr.audentia.protect.main.AudentiaProtect
version: 0.1.0
authors:
  - LukaMrt
api-version: "1.16"
softdepend:
  - "Audentia-Players"
commands:
  reloadsigns:
    description: reload all house signs
  newhouse:
    description: start new house creation