[bank]
npcName = "Tony"

[game]
time_protection = 60   # En minutes, les 15 premières minutes exclusives aux légats sont comprises

[border]
size = 314    # Longueur d'un côté du carré formé par la bordure
x = 0
z = 0

[city]
radius = 10    # Longueur du rayon de la cité
x = 0
z = 0

[coliseum]
radius = 10    # Longueur du rayon du colisée
x = 0
y = 60
z = 0
