name = "Tom"
count = 3

[locations]

    [0]
    x = 0
    y = 0
    z = 0
    yaw = 0
    pitch = 0

    [1]
    x = 0
    y = 0
    z = 0
    yaw = 0
    pitch = 0

    [2]
    x = 0
    y = 0
    z = 0
    yaw = 0
    pitch = 0