npc_name = "Tom"
locations_count = 3

[hours]
start_hour = 17
start_minutes = 30
end_hour = 19
end_minutes = 30

[shop]
items = [
    "EMERALD",
    "DIAMOND_SWORD"
]
EMERALD = 10.0
DIAMOND_SWORD = 20.0

[locations]

    [0]
    x = 0
    y = 0
    z = 0
    yaw = 0.0
    pitch = 0.0

    [1]
    x = 0
    y = 0
    z = 0
    yaw = 0.0
    pitch = 0.0

    [2]
    x = 0
    y = 0
    z = 0
    yaw = 0.0
    pitch = 0.0
