names = [
    "Manu"
]

[npcs]

    [Tony]  # PNJ de la banque à ne pas oublier
    x = 0
    y = 0
    z = 0
    yaw = 0
    pitch = 0

    [Manu]
    x = 0
    y = 0
    z = 0
    yaw = 0
    pitch = 0
